name: vocaleye
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences:
  fluttertoast:
  curved_navigation_bar:
  cupertino_icons: ^1.0.8
  intl:
  flutter_svg:
  image_picker:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  flutter_lints: ^5.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"



flutter:
  assets:
    - assets/images/

  uses-material-design: true
